package br.com.ifitness.model.ficha.assessment;

public enum MeasurementsType {
	DOBRA_CUTANEA_SUBESCAPULAR,
	DOBRA_CUTANEA_SUPRAILIACA,
	DOBRA_CUTANEA_TRICIPITAL,
	DOBRA_CUTANEA_BICIPITAL,
	DOBRA_CUTANEA_ABDOMINAL,
	DOBRA_CUTANEA_COXA_MEDIAL,
	DOBRA_CUTANEA_PEITORAL,
	DOBRA_CUTANEA_AXILAR_MEDIA,
	DOBRA_CUTANEA_PANTURRILHA_MEDIAL;
}
